use_nerdfont = true
volnorm = true
notify = true
bitrate = 320
flip_status_indicators = true
initial_screen = "queue"

[keybindings]
# "q" = "back"
"." = "seek +1000"
"," = "seek -1000"
">" = "next"
"<" = "previous"

[theme]
background = "default"
primary = "#EBDBB2"
secondary = "#D5C4A1"
title = "#689D6A"
playing = "#689D6A"
playing_selected = "#458588"
playing_bg = "default"
highlight = "#D79921"
highlight_bg = "default"
error = "#FBF1C7"
error_bg = "#CC241D"
statusbar_bg = "default"
statusbar_progress = "#689D6A"
statusbar = "#689D6A"
cmdline = "default"
cmdline_bg = "#FE8019"
# search_match = "#D79921"
